name: Deploy Plugin to Deno Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Deploy Plugin
        uses: ./.github/actions/plugin-deploy
        with:
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          pluginEntry: "./worker"
          # organization: "your-org-name" # Optional
