name: Deploy Hello World App

on:
  push:
    branches: [main]
    paths:
      - 'apps/hello-world/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/deno-deploy-template.yml'

jobs:
  deploy:
    uses: ./.github/workflows/deno-deploy-template.yml
    with:
      project_prefix: hw-app
      file_path: apps/hello-world/main.ts
      entrypoint: main.ts
      # organization_id is now optional - will use token holder's default org
    secrets:
      DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
