name: Deploy to Deno Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC authentication
      contents: read     # Required to access repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: hello-world-app
          entrypoint: apps/hello-world/main.ts
