name: Deploy Hello World App

on:
  push:
    branches: [main]
    paths:
      - 'apps/hello-world/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/deno-deploy-template.yml'

jobs:
  deploy:
    uses: ./.github/workflows/deno-deploy-template.yml
    with:
      project_prefix: hw-app
      file_path: apps/hello-world/main.ts
      entrypoint: main.ts
      organization_id: 1f86cd68-1bbf-4ac5-8d31-b6096bee31f0
    secrets:
      DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
